spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: local
server:
  port: 8123

## Mybatis
mybatis-plus:
  global-config:
    sql-parser-cache: false
    db-config:
      id-type: uuid
  configuration:
    cache-enabled: false

## Swagger
swagger:
  enable: true
  title: Swagger Api Console
  description:
  version: 1.0
  contact:
    name: ivan
    url: a.b.c.d
    mail: a@b.c.d

## Log path
logging:
  path: logs/zoffy

