spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/chinook
    username: postgres
    password: 1qaw3@123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        integrator_provider: top.moma.zoffy.config.HibernateIntegratorProvider
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.moma.zoffy
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn